FROM ghcr.io/archlinux/archlinux:base-devel-20260718.0.557885 AS base_image

# Signatures expire, repos expire, and so on. Make this image reproducible
# (update this once in a while)
RUN sed -i "s/^SigLevel.*/SigLevel = Never/;/DisableSandbox/s/^#//" /etc/pacman.conf && \
    echo 'Server=https://archive.archlinux.org/repos/2026/07/18/$repo/os/$arch' > /etc/pacman.d/mirrorlist

RUN pacman -Syyuu --noconfirm && \
    pacman -Fy

FROM base_image AS test_image

COPY ./test_runner_inner.sh /test_runner_inner.sh

ENV CI=1
ENV RUST_BACKTRACE=1
ENV NO_COLOR=1
