name: Build (helper)

permissions:
  contents: read

on:
  workflow_call:

env:
  CARGO_INCREMENTAL: 0
  CARGO_PROFILE_DEV_DEBUG: 0
  CARGO_TERM_COLOR: always
  FILKOLL_BUILDER: github-ci
  RUST_BACKTRACE: 1
  CC: clang
  RUSTFLAGS: "-D warnings"
  RUSTUP_MAX_RETRIES: 10

jobs:
  modern-default:
    # Test modern compilers on standard platforms on Linux.
    name: "${{ matrix.target }} - ${{ matrix.rust }} (default configuration)"
    runs-on: ubuntu-latest
    env:
      CARGO_PROFILE_DEV_DEBUG: 1
      CARGO_PROFILE_DEV_SPLIT_DEBUGINFO: ${{ matrix.debug_info }}
      RUSTFLAGS: -D warnings -Clink-arg=-Wl,--compress-debug-sections=zlib
    strategy:
      fail-fast: false
      matrix:
        target:
          - aarch64-unknown-linux-gnu
          - aarch64-unknown-linux-musl
          - armv7-unknown-linux-gnueabihf
          - armv7-unknown-linux-musleabihf
          - i686-unknown-linux-gnu
          - i686-unknown-linux-musl
          - x86_64-unknown-linux-gnu
          - x86_64-unknown-linux-musl
        rust:
          - stable
          - nightly
        debug_info:
          - packed
        include:
          # RISCV doesn't work with split debug info (see rust-lang/rust#110224)
          - target: riscv64gc-unknown-linux-gnu
            rust: stable
            debug_info: off
          - target: riscv64gc-unknown-linux-gnu
            rust: nightly
            debug_info: off
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Install Rust
        run: rustup install --profile minimal ${{ matrix.rust }} && rustup default ${{ matrix.rust }}
      - name: Print environment info
        run: |
          echo "# Rust"
          rustc -Vv
          echo "# Cargo"
          cargo -Vv
          echo "# GCC"
          gcc -v
          echo "# Clang"
          clang -v
          echo "# Ld"
          ld -v
      - name: Install cross
        uses: taiki-e/install-action@cross
      - name: Cache builds
        uses: Swatinem/rust-cache@v2.7.7
        with:
          key: ${{ matrix.target }}-${{ matrix.rust }}
      - name: Cross compile binary
        run: cross build --locked --target ${{ matrix.target }} --verbose
      - name: Cross compile tests
        run: cross test --no-run --locked --target ${{ matrix.target }} --verbose
      - name: Cross test
        run: cross test --locked --target ${{ matrix.target }} --verbose
      - name: Compress binary
        if: matrix.rust == 'stable' && contains(matrix.target, 'musl')
        run: |
          mkdir filkoll
          cp target/${{ matrix.target }}/debug/filkoll filkoll/
          if [[ -f target/${{ matrix.target }}/debug/filkoll.dwp ]]; then
            # No split debug info for RISCV
            cp target/${{ matrix.target }}/debug/filkoll.dwp filkoll/
          fi
          tar cf filkoll.tar filkoll
          zstd -T0 -6 filkoll.tar
      - uses: actions/upload-artifact@v4
        if: matrix.rust == 'stable' && contains(matrix.target, 'musl')
        with:
          name: filkoll_${{ matrix.target }}.tar.zst
          path: filkoll.tar.zst
          retention-days: 7
      - name: Clean up temporary items
        run: |
          rm -rf filkoll filkoll.tar filkoll.tar.zst

  configurations:
    # Test non-standard configurations, MSRV and Rust versions
    name: "Test: \"${{ matrix.features }}\" (Linux), Rust ${{ matrix.rust }}"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        features:
          - --all-features
        rust:
          - 1.85.0
          - stable
        include:
          # MSRV with default features too
          - features:
            rust: 1.85.0
          # Nightly will all features
          - features: --all-features
            rust: nightly
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Install Rust
        run: rustup install --profile minimal  ${{ matrix.rust }} && rustup default ${{ matrix.rust }}
      - name: Get cargo-binstall
        run: |
          curl -L https://github.com/cargo-bins/cargo-binstall/releases/latest/download/cargo-binstall-x86_64-unknown-linux-musl.tgz | tar -zxf - && mv cargo-binstall $HOME/.cargo/bin/
      - name: Cache builds
        uses: Swatinem/rust-cache@v2.7.7
      - name: Compile
        run: cargo test --locked ${{ matrix.features }} --verbose --no-run
      - name: Test
        run: cargo test --locked ${{ matrix.features }} --verbose
    env:
      # Warnings are ok for now here due to private APIs that will be public in the future.
      RUSTFLAGS: ""
      # TODO: Implement integration tests
      #integration:
      #  name: "Integration tests"
      #  runs-on: ubuntu-24.04
      #  needs: modern-default
      #  steps:
      #    - uses: actions/checkout@v4
      #      with:
      #        persist-credentials: false
      #    - uses: actions/download-artifact@v4
      #      with:
      #        name: filkoll_x86_64-unknown-linux-musl.tar.zst
      #    - name: Unpack binaries
      #      run: |
      #        tar xf ${GITHUB_WORKSPACE}/filkoll.tar.zst
      #        mkdir -p target/debug
      #        mv filkoll/* target/debug/
      #    - name: Install podman
      #      run: |
      #        sudo apt-get update
      #        sudo apt-get install -y podman
      #        podman --version
      #    - name: Run integration tests
      #      run: |-
      #        cd integration_tests
      #        ./run_tests.sh
